In [3]:
import  pandas as pd
import numpy as np
import selenium

In [22]:
df = pd.read_csv('kursach_16.11.24.csv', sep=';')
df

,Unnamed: 0,Event ID,Event Date,Event Text,Story ID,City,District,Province,Latitude,Longitude,Year
0,0,37542234,2022-10-14,Criticize or denounce,56633063,NaN,NaN,NaN,55.7522,37.6156,2022
1,1,37536358,2022-10-18,Criticize or denounce,56617379,Moscow,NaN,Moskva,55.7522,37.6156,2022
2,2,37536357,2022-10-18,Make pessimistic comment,56617379,Moscow,NaN,Moskva,55.7522,37.6156,2022
3,3,37536359,2022-10-18,Express intent to provide military aid,56617388,Moscow,NaN,Moskva,55.7522,37.6156,2022
4,4,37538604,2022-10-18,Criticize or denounce,56623802,Moscow,NaN,Moskva,55.7522,37.6156,2022
...,...,...,...,...,...,...,...,...,...,...,...
1199578,1199578,37532178,2023-01-03,Make statement,56607805,Moscow,NaN,Moskva,55.7522,37.6156,2023
1199579,1199579,37532494,2023-01-03,Use conventional military force,56607853,Moscow,NaN,Moskva,55.7522,37.6156,2023
1199580,1199580,37532350,2023-01-03,Make statement,56608467,NaN,NaN,NaN,55.7522,37.6156,2023
1199581,1199581,37532359,2023-01-03,Use conventional military force,56608467,NaN,NaN,NaN,55.7522,37.6156,2023
1199582,1199582,37532601,2023-01-03,Make statement,56608637,Makeyevka,NaN,Bashkortostan,53.3833,55.5833,2023

In [4]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import time

In [5]:
service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome()

In [6]:
ref = 'http://google.com'
driver.get(ref)

In [7]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time
import pandas as pd

In [ ]:
# Указываем путь к WebDriver
# driver_path = "path/to/chromedriver"  # Укажите путь к драйверу
driver = webdriver.Chrome()

# Открываем Яндекс.Карты
driver.get("https://yandex.ru/maps/")
time.sleep(3)  # Ждём загрузки страницы

In [17]:
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [ ]:
def get_municipality(latitude, longitude):
    try:

        # Находим поле поиска

        search_box = driver.find_element(By.CSS_SELECTOR, "input.input__control")
        search_box.clear()

        # Вводим координаты
        coordinates = f"{latitude}, {longitude}"
        search_box.send_keys(coordinates)
        print(Keys.RETURN)
        search_box.send_keys(Keys.RETURN)
        time.sleep(2)  # Ждём загрузки результата

        # Извлекаем информацию о муниципалитете
        # Считываем первый результат в правом блоке
        search_box = WebDriverWait(driver, 10).until(
                EC.visibility_of_element_located((By.CSS_SELECTOR, 'div.toponym-card-title-view__description'))
            )

        municipality = search_box.text
        print(municipality)
        search_box = driver.find_element(By.XPATH, "//button[contains(@aria-label, 'Закрыть')]") 
        search_box.click()

        return municipality
    except Exception as e:
        print(f"Ошибка: {e}")
        return None

In [ ]:


# Создаём столбец для результатов
df["municipality"] = None
cnt = 0
# Парсим каждую координату
for idx, row in df.iterrows():
    if (cnt > 100):
        break
    cnt += 1
    latitude = row["Latitude"]
    longitude = row["Longitude"]
    municipality = get_municipality(latitude, longitude)
    df.at[idx, "municipality"] = municipality
    print(f"Координаты ({latitude}, {longitude}) -> {municipality}")

# Сохраняем результаты в файл
df.head()


Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Гайский муниципальный округ, Оренбургская область
Координаты (51.4, 58.6167) -> Гайский муниципальный округ, Оренбургская область

Гайский муниципальный округ, Оренбургская область
Координаты (51.4, 58.6167) -> Гайский муниципальный округ, Оренбургская область

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Гайский муниципальный округ, Оренбургская область
Координаты (51.4, 58.6167) -> Гайский муниципальный округ, Оренбургская область

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Комсомольская улица, 19, село Черкассы, Елецкий район, Липецкая область, 399768
Координаты (52.6959, 38.7262) -> Комсомольская улица, 19, село Черкассы, Елецкий район, Липецкая область, 399768

1-й Михайловский проезд, Михайловский район, Рязань
Координаты (54.6269, 39.6916) -> 1-й Михайловский проезд, Михайловский район, Рязань

1-й Михайловский проезд, Михайловский район, Рязань
Координаты (54.6269, 39.6916) -> 1-й Михайловский проезд, Михайловский район, Рязань

1-й Михайловский проезд, Михайловский район, Рязань
Координаты (54.6269, 39.6916) -> 1-й Михайловский проезд, Михайловский район, Рязань

1-й Михайловский проезд, Михайловский район, Рязань
Координаты (54.6269, 39.6916) -> 1-й Михайловский проезд, Михайловский район, Рязань

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Гайский муниципальный округ, Оренбургская область
Координаты (51.4, 58.6167) -> Гайский муниципальный округ, Оренбургская область

Гайский муниципальный округ, Оренбургская область
Координаты (51.4, 58.6167) -> Гайский муниципальный округ, Оренбургская область

Дворцовая площадь, Санкт-Петербург
Координаты (59.9386, 30.3141) -> Дворцовая площадь, Санкт-Петербург

Дворцовая площадь, Санкт-Петербург
Координаты (59.9386, 30.3141) -> Дворцовая площадь, Санкт-Петербург

проспект Богдана Хмельницкого, 80, Белгород
Координаты (50.6107, 36.5802) -> проспект Богдана Хмельницкого, 80, Белгород

Муезерское городское поселение, Республика Карелия
Координаты (64.0, 32.5) -> Муезерское городское поселение, Республика Карелия

деревня Терехово, Пановское сельское поселение, Палехский район, Ивановская область
Координаты (56.7473, 42.0496) -> деревня Терехово, Пановское сельское поселение, Палехский район, Ивановская область

деревня Терехово, Пановское сельское поселение, Палехский район, Ивановская область
Координаты (56.7473, 42.0496) -> деревня Терехово, Пановское сельское поселение, Палехский район, Ивановская область

Малый Кремлёвский сквер, Москва
Координаты (55.7517, 37.6178) -> Малый Кремлёвский сквер, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Ленинский район, городской округ Челябинск
Координаты (55.154, 61.4291) -> Ленинский район, городской округ Челябинск

аллея Строителей, Центральный округ, Омск
Координаты (54.9924, 73.3686) -> аллея Строителей, Центральный округ, Омск

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Гайский муниципальный округ, Оренбургская область
Координаты (51.4, 58.6167) -> Гайский муниципальный округ, Оренбургская область

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Гайский муниципальный округ, Оренбургская область
Координаты (51.4, 58.6167) -> Гайский муниципальный округ, Оренбургская область

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Малый Кремлёвский сквер, Москва
Координаты (55.7517, 37.6178) -> Малый Кремлёвский сквер, Москва

деревня Овсянниково, муниципальное образование Тургеневское, Чернский район, Тульская область
Координаты (53.4834, 36.6347) -> деревня Овсянниково, муниципальное образование Тургеневское, Чернский район, Тульская область

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Малый Кремлёвский сквер, Москва
Координаты (55.7517, 37.6178) -> Малый Кремлёвский сквер, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

деревня Овсянниково, муниципальное образование Тургеневское, Чернский район, Тульская область
Координаты (53.4834, 36.6347) -> деревня Овсянниково, муниципальное образование Тургеневское, Чернский район, Тульская область

деревня Овсянниково, муниципальное образование Тургеневское, Чернский район, Тульская область
Координаты (53.4834, 36.6347) -> деревня Овсянниково, муниципальное образование Тургеневское, Чернский район, Тульская область

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Гайский муниципальный округ, Оренбургская область
Координаты (51.4, 58.6167) -> Гайский муниципальный округ, Оренбургская область

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Малый Кремлёвский сквер, Москва
Координаты (55.7517, 37.6178) -> Малый Кремлёвский сквер, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Транспортный переулок, 7, Красноярск, 660060
Координаты (56.0184, 92.8672) -> Транспортный переулок, 7, Красноярск, 660060

Транспортный переулок, 7, Красноярск, 660060
Координаты (56.0184, 92.8672) -> Транспортный переулок, 7, Красноярск, 660060

Транспортный переулок, 7, Красноярск, 660060
Координаты (56.0184, 92.8672) -> Транспортный переулок, 7, Красноярск, 660060

Транспортный переулок, 7, Красноярск, 660060
Координаты (56.0184, 92.8672) -> Транспортный переулок, 7, Красноярск, 660060

49К-13, Новгородская область
Координаты (58.7417, 33.5026) -> 49К-13, Новгородская область

1-й Михайловский проезд, Михайловский район, Рязань
Координаты (54.6269, 39.6916) -> 1-й Михайловский проезд, Михайловский район, Рязань

1-й Михайловский проезд, Михайловский район, Рязань
Координаты (54.6269, 39.6916) -> 1-й Михайловский проезд, Михайловский район, Рязань

1-й Михайловский проезд, Михайловский район, Рязань
Координаты (54.6269, 39.6916) -> 1-й Михайловский проезд, Михайловский район, Рязань

1-й Михайловский проезд, Михайловский район, Рязань
Координаты (54.6269, 39.6916) -> 1-й Михайловский проезд, Михайловский район, Рязань

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва
Координаты (55.7522, 37.6156) -> Троицкая улица, Кремль, Тверской район, Центральный административный округ, Москва

Гайский муниципальный округ, Оренбургская область
Координаты (51.4, 58.6167) -> Гайский муниципальный округ, Оренбургская область

1-й Михайловский проезд, Михайловский район, Рязань
Координаты (54.6269, 39.6916) -> 1-й Михайловский проезд, Михайловский район, Рязань

1-й Михайловский проезд, Михайловский район, Рязань
Координаты (54.6269, 39.6916) -> 1-й Михайловский проезд, Михайловский район, Рязань

,Unnamed: 0,Event ID,Event Date,Event Text,Story ID,City,District,Province,Latitude,Longitude,Year,municipality
0,0,37542234,2022-10-14,Criticize or denounce,56633063,NaN,NaN,NaN,55.7522,37.6156,2022,"Троицкая улица, Кремль, Тверской район, Центра..."
1,1,37536358,2022-10-18,Criticize or denounce,56617379,Moscow,NaN,Moskva,55.7522,37.6156,2022,"Троицкая улица, Кремль, Тверской район, Центра..."
2,2,37536357,2022-10-18,Make pessimistic comment,56617379,Moscow,NaN,Moskva,55.7522,37.6156,2022,"Троицкая улица, Кремль, Тверской район, Центра..."
3,3,37536359,2022-10-18,Express intent to provide military aid,56617388,Moscow,NaN,Moskva,55.7522,37.6156,2022,"Троицкая улица, Кремль, Тверской район, Центра..."
4,4,37538604,2022-10-18,Criticize or denounce,56623802,Moscow,NaN,Moskva,55.7522,37.6156,2022,"Троицкая улица, Кремль, Тверской район, Центра..."

In [ ]:
# df.to_csv('dfgjfhdfogn.csv')